# Generated by Django 4.2.7 on 2026-09-01 06:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0017_cashflow_debtor_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignincome',
            name='foreign_interest_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest earned on foreign bank deposits / investments', max_digits=15),
        ),
    ]
