# Generated by Django 4.2.7 on 2026-09-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0018_foreignincome_foreign_interest_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localemploymentincome',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_employments', to='tax_forms.taxsubmission'),
        ),
    ]
