# Generated by Django 4.2.7 on 2026-09-02 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0019_local_employment_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcredits',
            name='tax_refund_claim',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refund claimed for tax withheld / paid in excess of the liability', max_digits=15),
        ),
    ]
