# Generated by Django 4.2.7 on 2026-09-02 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0020_taxcredits_tax_refund_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcredits',
            name='wht_brought_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Unused WHT credit carried forward from last Y/A (prefilled from last year's carry-forward; editable)", max_digits=15),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='wht_carried_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
