# Generated by Django 4.2.7 on 2026-09-03 05:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0021_wht_carry_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsubmission',
            name='capital_gain_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
