# Generated by Django 4.2.7 on 2026-09-03 09:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0022_capital_gain_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendincome',
            name='final_wht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final WHT deducted on exempt dividends, per the dividend certificate', max_digits=15),
        ),
        migrations.AlterField(
            model_name='dividendincome',
            name='exempt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross dividends from resident companies subject to final WHT — exempt from tax', max_digits=15),
        ),
    ]
