# Generated by Django 4.2.7 on 2026-09-04 04:35

from django.db import migrations
import encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0023_dividend_final_wht'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignincome',
            name='foreign_employer_name',
            field=encrypted_fields.EncryptedCharField(blank=True, help_text='Name of the foreign employer / company paying the income', max_length=200, null=True),
        ),
    ]
