# Generated by Django 4.2.7 on 2026-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0024_foreignincome_employer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_reminder_10d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_reminder_3d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_reminder_5d_sent',
            field=models.BooleanField(default=False),
        ),
    ]
