# Generated by Django 4.2.7 on 2026-09-10 08:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0025_taxsubmission_payment_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcredits',
            name='refund_brought_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="60% of last Y/A's unused refund entitlement, claimable as a tax credit this year (prefilled from last year's carry-forward; editable)", max_digits=15),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='refund_carried_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
