# Generated by Django 4.2.7 on 2026-09-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0026_taxcredits_refund_brought_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalofasset',
            name='is_capital_gain',
            field=models.BooleanField(default=False),
        ),
    ]
