# Generated by Django 4.2.7 on 2026-08-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_scheduledmessage_scheduledmessagerecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessagerecipient',
            options={'ordering': ['id']},
        ),
    ]
