# Generated by Django 4.2.7 on 2026-09-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_scheduledmessagerecipient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='notifications.scheduledmessage')),
            ],
            options={
                'db_table': 'scheduled_message_campaigns',
            },
        ),
    ]
